# Generated by Django 2.0 on 2019-03-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190312_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Month',
            field=models.DateField(default='March', max_length=100),
        ),
    ]
