# Generated by Django 2.0 on 2019-03-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190313_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='If_Others_Please_Specify',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Month',
            field=models.CharField(default='March', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Remediation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Resolution',
            field=models.TextField(null=True),
        ),
    ]
