# Generated by Django 2.0 on 2019-03-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190317_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Escalated',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='False_Alarm',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='Priority',
            field=models.TextField(),
        ),
    ]
