# Generated by Django 2.0 on 2019-12-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20190515_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Interval',
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateField(db_column='dete', default='2019-12-12'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Mode_of_Alert',
            field=models.TextField(db_column='mode', default='Manual'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Month',
            field=models.CharField(db_column='menth', default='December', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Shift',
            field=models.TextField(db_column='shyft', default='USA'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Week',
            field=models.CharField(db_column='weekno', default='Week 50', max_length=20, null=True),
        ),
    ]
